//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDS_IDLE                        1
#define ERR_UNKNOWN                     2
#define ERR_CAPCONNECT                  3
#define ERR_CREATEICON                  4
#define ERR_WNDCLASS                    5
#define ERR_CREATEPREVIEWWINDOW         6
#define ERR_CREATEMAINWINDOW            7
#define ERR_NOCAMERA                    8
#define ERR_GDIPLUSSTARTUP              9
#define ERR_CAPTURE                     10
#define ERR_CONNECT                     11
#define SUCCESS_UPLOADED_IMAGE          12
#define IDS_SECONDS                     13
#define IDS_MINUTES                     14
#define IDS_HOURS                       15
#define STATUS_CONNECTING               16
#define STATUS_UPLOADING                17
#define STATUS_CHDIR                    18
#define ERR_UPLOAD                      19
#define ERR_INTERNETOPEN                20
#define IDS_DEVICE_CHANGED              21
#define ERR_UPLOAD_DIRECTORY            22
#define ERR_BALLOONTITLE                23
#define ERR_COINIT                      24
#define ERR_CREATEGRAPHBUILDER          25
#define ERR_CREATEVIDEORENDERER         26
#define ERR_ADDVIDEORENDERER            27
#define ERR_NOVIDEOCAPTURE              28
#define ERR_ADDVIDEOCAPTURE             29
#define ERR_CREATECAPTUREGRAPHBUILDER   30
#define ERR_SETFILTERGRAPH              31
#define ERR_RENDERSTREAM                32
#define ERR_CREATESMARTTEE              33
#define ERR_ADDSMARTTEE                 34
#define ERR_CREATEGRABBER               35
#define ERR_CREATENULLRENDERER          36
#define ERR_ADDNULLRENDERER             37
#define ERR_ADDGRABBER                  38
#define ERR_QUERYGRABBER                39
#define ERR_SETMEDIATYPE                40
#define IDS_IMAGESIZESMALL              41
#define IDS_IMAGESIZEMEDIUM             42
#define IDS_IMAGESIZELARGE              43
#define IDS_IMAGESIZEXLARGE             44
#define ERR_MODIFYVIDEOFORMAT           45
#define IDS_APPNAME                     46
#define ERR_MODIFYVIDCAP                47
#define IDS_PREVIEWWINDOWTITLE          48
#define IDS_SETTINGS                    49
#define ERR_TVTUNERPROPERTIES           50
#define IDS_UPPERLEFT                   51
#define IDS_TOP                         52
#define IDS_UPPERRIGHT                  53
#define IDS_LEFT                        54
#define IDS_CENTRE                      55
#define IDS_RIGHT                       56
#define IDS_LOWERLEFT                   57
#define IDS_BOTTOM                      58
#define IDS_LOWERRIGHT                  59
#define IDS_BG_SOLID                    60
#define IDS_BG_TRANSLUCENT              61
#define IDS_BG_NONE                     62
#define ERR_EXPIRED                     63
#define ERR_CREATE_CHOOSE_VIDEO_DEVICE_DIALOG 64
#define IDS_DEVICE_CHANGED_TITLE        65
#define STATUS_FTP_TIMEOUT              66
#define IDD_MAIN                        101
#define IDI_APPICON                     102
#define IDD_FTP                         107
#define IDD_VIDEO                       108
#define IDD_EFFECTS                     109
#define IDD_OVERLAY                     111
#define IDB_OVERLAYPREVIEW              117
#define IDD_CHOOSE_VIDEO_DEVICE         118
#define IDC_BTNPREVIEW                  1000
#define IDC_BTNEXIT                     1001
#define IDC_BTNCAPTURE                  1003
#define IDC_FTPSERVER                   1004
#define IDC_DIRECTORY                   1005
#define IDC_FILENAME                    1006
#define IDC_TIMEVALUE                   1007
#define IDC_SPINTIME                    1008
#define IDC_TIMEUNIT                    1009
#define IDC_STATUS                      1011
#define IDC_BTNVIDCAPPROPERTIES         1014
#define IDC_USERNAME                    1016
#define IDC_PASSWORD                    1017
#define IDC_DIALUP                      1019
#define IDC_RUNATSTARTUP                1020
#define IDC_BTNVIDEOFORMAT              1022
#define IDC_TIMESTAMP                   1023
#define IDC_WISDOM                      1024
#define IDC_IMAGESIZE                   1025
#define IDC_PREVIEW                     1029
#define IDC_BTNSETTINGS                 1030
#define IDC_FONTLIST                    1031
#define IDC_FONTSIZE                    1032
#define IDC_SPINFONTSIZE                1033
#define IDC_FONTBOLD                    1034
#define IDC_FONTITALIC                  1035
#define IDC_FONTUNDERLINE               1036
#define IDC_FONTSTRIKEOUT               1037
#define IDC_SMOOTHNONE                  1038
#define IDC_SMOOTHSTANDARD              1039
#define IDC_SMOOTHCLEARTYPE             1040
#define IDC_VIDEOSOURCE                 1041
#define IDC_BTNTVTUNER                  1042
#define IDC_BTNFGCOLOUR                 1043
#define IDC_BTN_CHANGE_VIDEO_DEVICE     1043
#define IDC_BTNBGCOLOUR                 1044
#define IDC_SAMPLETEXT                  1045
#define IDC_FLIPHORIZONTAL              1046
#define IDC_FLIPVERTICAL                1047
#define IDC_PASSIVEFTP                  1048
#define IDC_TEXTPOSITION                1049
#define IDC_FONTSHADOW                  1050
#define IDC_BGSTYLE                     1051
#define IDC_JPEGQUALITY                 1052
#define IDC_BTNHOMEPAGE                 1055
#define IDC_DATESTAMP                   1057
#define IDC_DISABLEFTP                  1059
#define IDC_LOCALFILENAME               1062
#define IDC_FILEBROWSE                  1063
#define IDC_SAVETOFILE                  1064
#define IDC_OPENFILE                    1065
#define IDC_DISABLETIMER                1066
#define IDC_OVERLAY_PREVIEW_FRAME       1069
#define IDC_EDIT1                       1070
#define IDC_OVERLAYFILENAME             1070
#define IDC_CUSTOMSIZEX                 1070
#define IDC_BUTTON1                     1071
#define IDC_OVLKEY_CHOOSE               1071
#define IDC_FILE_DEVICE_BROWSE          1071
#define IDC_BUTTON2                     1072
#define IDC_FILEBROWSE_OVERLAY          1072
#define IDC_OVERLAYFILE_CLEAR           1073
#define IDC_OVLSCALE_BESTFIT            1074
#define IDC_OVLSCALE_ORIGINAL           1075
#define IDC_OVLSCALE_PERCENT            1076
#define IDC_OVLSCALE_EDIT               1077
#define IDC_OVLSCALE_SLIDER             1078
#define IDC_OVLOPACITY_SLIDER           1079
#define IDC_OVLOPACITY_EDIT             1080
#define IDC_OVLPOS_LIST                 1081
#define IDC_OVLPOS_X                    1082
#define IDC_OVLKEY_CHK                  1087
#define IDC_OVLKEY_STATIC               1088
#define IDC_RADIOSTDSIZE                1089
#define IDC_RADIOCUSTOMSIZE             1090
#define IDC_CUSTOMSIZEY                 1091
#define IDC_CROP_ENABLE                 1092
#define IDC_CROP_Y                      1093
#define IDC_CROP_X                      1094
#define IDC_CROP_WIDTH                  1095
#define IDC_CROP_HEIGHT                 1096
#define IDC_VIDEO_DEVICE_NAME           1097
#define IDC_COMBO_VIDEO_DEVICE          1098
#define IDC_RADIO_DEVICE_FILE           1099
#define IDC_RADIO_DEVICE_CAMERA         1100
#define IDC_FILE_DEVICE_PATH            1101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
